### ISSUE TITLE
Vim plugin - call to `get_end_location` fails for `cc` command

### ISSUE THREAD

**Issue by andy-lang** [AdaCore/gnatstudio#12]
In usual Vim contexts, typing `cc` should delete the entirety of the current line and put the environment into insert mode. However, doing so with GPS' `vim` plugin causes the following stacktrace, with no change to the contents of the editor:

```pycon
Traceback (most recent call last):
  File "/opt/gps/share/gps/library/vim.py", line 753, in key_pressed_proxy
    return view.vim_state.on_key_pressed(view, event)
  File "/opt/gps/share/gps/library/vim.py", line 284, in on_key_pressed
    remember_action = action.apply()
  File "/opt/gps/share/gps/library/vim.py", line 502, in apply
    BaseAction.apply(self)
  File "/opt/gps/share/gps/library/vim.py", line 345, in apply
    action.apply_action()
  File "/opt/gps/share/gps/library/vim.py", line 537, in apply_action
    end_loc = self.expected_action.get_end_location()
AttributeError: 'Replace' object has no attribute 'get_end_location'
```

**Comment by AnthonyLeonardoGracio** [comment]
Hello Andy, 

We are able to reproduce the issue indeed. Tanks for the report!
